import os
import sys

# The raw list of packages to search for
# Categories (e.g. "Shopping") will be filtered out automatically based on the lack of '.'
TARGET_LIST_RAW = """
ma.safe.bnnigeria
com.google.android.apps.magazines
tech.livestate.dailynews
bbc.mobile.news.ww
ma.safe.bnus
com.newsbreak.app
us.usa.news.app
com.republicworld
com.zumobi.msnbc
com.news.app.global
com.tvchannels.pakistantv
com.local.news.plus
com.nytimes.android
com.news.app.global.bite
com.abc.abcnews
com.local.news.radar
rim.info.app
com.grimbyte.newsbreaksite
com.life360.android.safetymapd
com.bskyb.skynews.android
com.haystack.android
ma.safe.bn
com.guardian
jp.gocro.smartnews.android
com.cnn.mobile.android.phone
com.opera.app.news
com.handmark.sportcaster
com.dailynews.globalnews.keepupwithevents
com.tradingview.tradingviewapp
com.republic.republicbusiness
com.opera.mini.native
com.bambuna.podcastaddict
mnn.Android
com.washingtonpost.android
com.onesports.livescore
com.huami.watch.hmwatchmanager
cn.museedu.scoreboard
bbc.mobile.sport.ww
com.scores.tfz
com.bskyb.fbscore
com.onesports.score
eu.livesport.FlashScore_com
com.freerange360.mpp.GOAL
com.livescore
com.yahoo.mobile.client.android.sportacular
com.sportsbrief.twa
com.matchplay.app
lunosoftware.scoresandodds
com.fivemobile.thescore
com.scoresandodds.mobile
com.espn.score_center
com.mobilefootie.wc2010
com.diyas.android.stumps
com.teamsnap.teamsnap
com.nbaimd.gametime.nba2011
com.homemade.ffm2
com.tsportszone.footballtvhd
com.allfootball.news
com.sofascore.results
com.betway.scores.android
lunosoftware.sportsalerts
com.handmark.sportcaster
com.dazn
de.motain.iliga
com.toddbrady.sportsscores
com.scores365
Food_and_Drinks
com.revolx.tasty.chef.cooking.game
com.project.kiranchavan.breakfastfree
com.cookware.worldcusinerecipes
com.endless.cookbook
com.kindrida.healthyRecipes
com.yelp.android
com.newandromo.dev728180.app3144911
us.thatrecipe
com.endless.kitchenbook
com.aquila.ketodiet.ketogenicdiet.lowcarbrecipes
com.tech.recipeapp
com.riatech.easyrecipes
com.recipebook.cake_recipes
com.meenstudio.bakingrecipes
com.magicforstudio.cookbookrecipes
com.kiransmoothie.kiranchavan.juicerecipe
easy.cooking.recipes
com.ajnsnewmedia.kitchenstories
com.magicforstudio.fastfoodrecipes
com.riatech.cookbook
com.colorgame.tastykitchen
com.application.zomato
com.kiranchavan.cookbook
com.aquila.tasty.recipes
com.kindrida.breakfastrecipes
com.alphazstudio.breakfastrecipes
com.n51951dd8177.app
id.kundev.nigerianrecipes
com.ubercab.eats
fr.cookbook
com.findmymobile.lostphone.phonetracker
mtr.cpumonitor.temperature
com.colorphone.flashalert.ringtones.callscreen.colorflashcall
smart.cleaner.clean.master.booster.free
com.supercleaner.antivirus.filemanager
cmu.cleanmaster.new.app
com.mobikeeper.global
qrcodescanner.barcodescanner.qrscanner.qrcodereader
org.nixgame.ruler
com.anti.virus.security
com.file.manager.file.organizer.file.explorer.manage.files
com.phone.cleaner.shineapps
com.ms.phonecleaner.clean.junk.apps
com.joshbrian.batterysaver.fastcharger.UltraPowerSaver
com.sp.protector.free
com.vincentlee.compass
cleaner.antivirus.cleaner.virus.clean.vpn
hotspotshield.android.vpn
com.piriform.ccleaner
com.geekyouup.android.widgets.battery
com.mi.android.globalFileexplorer
com.wifianalyzer.showwifipassword.wifiqr.wifimaster.speedtest
fileexplorer.files.filemanager.tool
antivirus.virus.cleaner.clean.vpn.booster
com.exatools.sensors
com.shwy.phone.space.cleaner
com.fast.free.unblock.secure.vpn
com.phonecleaner.storagecleaner.junkcleaner.cleanphone
com.avast.android.cleaner
com.eliteantivirus.booster.applock
com.filemanager.managefile.fileexplorer.fileextractor
com.applus.torch.light.flashlight.flashalert
com.nirmallabs.sensorbox
com.mtdl.superbattery.chargemonitor
com.alphainventor.filemanager
Shopping
scanner.pdf.ocr
com.appkarma.app
com.groupon
com.rayolesoftware.tapnearn
com.thekrazycouponlady.kcl
com.couponat.promocodecouponsshein
geekshop.onlineshopping
com.amazon.mShop.android.shopping
com.carauctionnetwork.publicautoauctions
com.minhtinh.outof.grocerylistapp
com.tradetu.compare.onlineshopping.shopping.app.browser
wb.receipts
com.furkandemir.weeklyads
uae.coupons.shopping
com.jumia.android
com.eco.grocerylist
br.com.duoli.pricecompare
com.ClickDeveloper.CouponsAppForFree.DealsVoucherPromoCodes
com.aaapp.appguru.usedcarsaleusa
com.gartorware.pantryapp
com.ebay.mobile
com.l
ch.publisheria.bring
com.headcode.ourgroceries
com.icedblueberry.shoppinglisteasy
com.ichota
io.kodular.tapansarkar702968.Allinone
com.buymeapie.bmap
Health_and_Fitness
com.tinymission.dailyabworkoutfree1
com.dailyyoga.inc
com.legend.pulsesync.app.android
pedometer.steptracker.calorieburner.stepcounter
com.despdev.weight_loss_calculator
increaseheightworkout.heightincreaseexercise.tallerexercise
com.gpsmaps.streetview.gpsnavigation.live.routefinder
homeworkout.homeworkouts.noequipment
steptracker.healthandfitness.walkingtracker.pedometer
face.yoga.exercise.massage.skincare
com.yazio.android
running.tracker.gps.map
com.fitnow.loseit
com.maps.locator.gps.gpstracker.phone
com.hrd.iam
pilatesworkout.yogaworkout.loseweight.workoutapps
com.maps.voice.navigation.traffic.gps.location.route.driving.directions
com.Bloodpressurerecorder.uill
menloseweight.loseweightappformen.weightlossformen
com.corusen.accupedo.te
pedometer.stepcounter.calorieburner.pedometerforwalking
com.popularapp.thirtydayfitnesschallenge
com.stepsappgmbh.stepsapp
net.workoutinc.butt_exercises_workouts
sixpack.sixpackabs.absworkout
fat.burnning.plank.fitness.loseweight
monitoryourweight.bustan.net
com.tinymission.dailyworkoutsfree
com.cronometer.android.gold
buttocksworkout.hipsworkouts.forwomen.legworkout
loseweight.weightloss.workout.fitness
Parenting
com.rz.pregnancy.guide
com.becloser
phonetracker.locationtracker.familylocator.trackingapp
com.YovoGames.babyCare2
qoresh.social.familyquotes
jp.co.sakabou.piyolog
com.sanaedutech.parenting
com.kinedu.appkinedu
simple.babytracker.newbornfeeding.babycare
pl.trpaslik.babynoise
kr.co.smartstudy.bbfbabycare_android_googlemarket
com.glow.android.baby
com.victoriadigitalagency.PositiveParentingStudyGuide
com.fofadtech.parenting_guides
com.drillyapps.babydaybook
i.am.com.affirmation
com.babycenter.pregnancytracker
com.amanefactory.totsukitoka
com.wte.view
com.hp.pregnancy.lite
com.coquisoft.parentlove
com.wachanga.babycare
com.dreamstudio.lullabies
com.hp.babyapp
com.pregnancy.due.date.calculator.tracker
com.whisperarts.erby
ru.mobiledimension.kbr
com.nighp.babytracker_android
com.neiman.contractions
com.amila.parenting
net.relaxio.babysleep
Social_media
com.plusme.live
com.nhn.android.band
kik.android
com.twitter.android
com.zhiliaoapp.musically
com.aigc.ushow.ichat
video.chat.joi
com.textmeinc.textme
jp.naver.line.android
ru.fotostrana.sweetmeet
co.ninecount.soda
com.mirrorai.app
com.guppir.swipr
com.rumble.battles
com.macrovideo.v380pro
com.appspot.scruffapp
com.hkfuliao.chamet
com.myyearbook.m
com.facebook.katana
com.yy.hiyo
com.dazz.hoop
com.pinkapp
com.superlive.liveapp
com.ihappydate
com.snapchat.android
com.jaumo.prime
com.instagram.android
com.taggedapp
com.reddit.frontpage
com.talkielive
com.google.android.youtube
com.pentabit.recommend.me.social
com.linkedin.android
uk.co.esfscorecentre.esf
com.eventpilot.epexpress
com.optimumbrewlab.invitationcardmaker
com.birthdayparty.eventplanner
com.meetup
uk.co.beyondlearning.eventcountdown
app.topevent.android
com.rqrapps.invitationcardmaker.greetingcards
works.jubilee.timetree
com.connectionevents.letsmeet
com.eventbrite.attendee
com.superb.rhv
com.peatix.android.Azuki
com.smule.magicpiano
uk.co.thestage.magazine
dk.whatshappening.app
com.smule.singandroid
com.bt.bms
com.sitix.app
tv.twitch.android.app
eu.spielwerk.thestage
com.etouches.loopdevents
com.greetingsisland.sam
com.timehop
com.aboutjsp.thedaybefore
com.letterboxd.letterboxd
Maps_and_Navigation
com.findmymobile.lostphone.phonetracker
com.gps.maps.navigation.routeplanner
com.navigationstreet.areafinder.livemaps.earthview.free
gps.speedometer.digihud.odometer
gps.speedometer.gpsspeedometer.odometer
com.waze
com.thetrainline
com.w.argps
com.mapzonestudio.gps.navigation.live.map.voice.translator
com.gpsnavigation.routeplanner.livemaproad.routefinder
com.prime.studio.apps.route.finder.map
com.virtualmaze.offlinemapnavigationtracker
com.viamichelin.android.viamichelinmobile
com.mapfactor.navigator
com.entertaininglogixapps.gps.navigation.direction.find.route.map.guide.pro
com.vialsoft.radarbot_free
com.kartatech.karta.gps
com.voice.navigation.driving.voicegps.map.directions
weather.forecast.rain.radar
com.virtualmaze.drivingroutefinder
com.citymapper.app.release
com.ktwapps.speedometer
aps.gpsmaps.voicenavigation
com.rapido.passenger
com.GPSnavigation.drivingdirections.GPS.Maps.voiceGPS
com.utrack.nationalexpress
com.live.earthmap.streetview.livecam
com.gpsnavigationmaps.routefinder
apps.r.speedometer
com.gpsnavigation.directions.gpsmaps
com.gpsnavigation.maps.gpsroutefinder.routemap
com.radarapp.trip.speedometer
com.gps.maps.trafficMap.compass.gpsroutefinder
livetraffic.mapswithme.maps.pro.maps.voice.directions.maps.app.gps.navigation.traffic.gps.location
com.voice.gps.driving.directions.gps.navigation.maps.location
io.mvlchain.tada
com.sharlocation.friend.family
Communication
com.textmeinc.freetone
wearos.smart.watch.bt.sync.notifier
com.hsv.freeadblockerbrowser
com.viber.voip
com.talknow.free.text.me.now.second.phone.number.burner.app
me.talkyou.app.im
com.google.android.gm
com.juphoon.justalk
me.number.app.im
com.eyecon.global
com.textmessages.chatandmessage
com.codebaker.textcall
org.telegram.messenger.web
com.michatapp.im
com.textmeinc.textme
call.blacklist.blocker
jp.naver.line.android
com.yahoo.mobile.client.android.mail
com.ertunga.wifihotspot
com.zing.zalo
sms.app.messages.app.message.box.message.me
com.imo.android.imous
com.hkfuliao.chamet
com.UCMobile.intl
gogolook.callgogolook2
com.textmessage.messenger
com.facebook.lite
com.dish.wireless.boostone
com.brave.browser
com.truecaller
com.cdyala.blazing
com.onlinemeeting.videomeeting.zoummeet.confrencemeet
com.kakao.talk
com.snapchat.android
app.source.getcontact
me.dingtone.app.im
com.messenger.sms.messages
com.mysecondline.app
com.jb.gosms
me.scrolla
com.callapp.contacts
com.messages.chattext
com.opera.browser
ru.mail.mailapp
com.native.messages
messenger.sms
com.whatsapp
Medical
com.fatbelly.firstaidsandemergencytechniques
com.medicaldictionary.diseasestreatment
com.ufo.disease
com.FriendsApp.SymptomChecker
br.com.caiocrol.alarmandpillreminder
com.soft24hours.directorys.medical.diseasemulti.free
com.dorular.medicaldictionary
com.medicalgroupsoft.medical.directorymedtermsmultilang.free
mand.mobilny.doktor
com.irwaa.medicareminders
com.webmd.android
com.yatrageng.home_remedies_all_diseases
com.medscape.android
com.diseases.treatment_dictionary
com.bestfuncoolapps.TakeYourPills
com.atomengineapps.teachmeanatomy
com.fatbelly.herbalhomeremedies
doctorram.medlist
com.gallant.home.treatment.doctorathome
com.drugscom.app
com.medicalgroupsoft.medical.refdiseases.eng.free
bp.bloodapp.surga.bloodtracker.app
com.teachmeseries.tmsurgery
com.atomic.apps.medical.disease.condition.dictionary
com.cameraprank.fullbody.xraybodyscanner
com.zeroapp.bloodpresshelp.app
com.ssstudio.anatomy
com.medisafe.android.client
com.FriendsApp.MedicalDrugsDictionary
com.drug.doctor
Books_Reference
com.liotek.lannbible
com.labs.merlinbirdid.app
com.bible.holy.bible.for.women
com.nirmallabs.novelsbooksinenglish
thxdroid.androidapp.translatepro
com.sirma.mobile.bible.android
com.stepstep.book
com.ibooktok.novel
app.hallow.android
com.biblelauncher.prayer.audiobiblekjv
wp.wattpad
com.mobisystems.msdict.embedded.wireless.oxford.dictionaryofenglish
com.basmo.BibleChat
com.radio.pocketfm
kjvbible.verse.daily.bible.prayer
com.translate.all.language.translator.dictionary.voice.translation
com.google.android.apps.books
kjv.bible.kingjamesbible
com.overdrive.mobile.android.libby
com.offline.bible
bible.kjvbible.audio.plan.verse
com.amazon.kindle
com.audible.application
com.novel.estory.free.reader.dreame.gp.us
com.mybible.todaypraybible
bible.offline.kingjames.holy.kjv.bible.daily.verse
studio.love.sweet.lessons.in.life.quotes
com.hoopladigital.android
in.banaka.mohit.english.novels.books
amen.blessed.app
Auto_and_Vehicles
com.min.car
com.iternio.abrpapp
com.struchev.car_expenses
br.com.ctncardoso.ctncar
com.xatori.Plugshare
com.autoscout24
com.adrianarias.autofixer.KTNCZ5P4H9
com.ovz.carscanner
com.carauctionnetwork.publicautoauctions
com.mapfactor.navigator
com.ballito.repair.fixproblems.update
com.zenthek.autozen
com.autouncle.autouncle
com.ovilex.drivingschoolsim
com.pnn.obdcardoctor
com.softartstudio.carwebguru
com.sec.automation
com.autochek.buysalefixcars
com.olzhas.carparking.multyplayer
com.car.repairs.problem.carproblemrepairs
com.fixeads.standvirtual
com.edmunds
mrigapps.andriod.fuelcons
com.zonewalker.acar
com.roadtrippers
com.newandromo.dev1595688.app2451618
com.andrzejsalwin.motorcyclefuellogfree
com.ScanMyOpelLite.Main
diagramasautomotrices.aplivln
com.dubicars.dubicars
Games
com.KillerBeanStudios.KillerBeanUnleashed
com.hyperkani.stuntcarextreme
com.vectorunit.purple.googleplay
com.halfbrick.dantheman
com.riseup.game
com.azurgames.stackball
com.tencent.ig
com.football.soccer.league
com.bitmango.rolltheballunrollme
com.easybrain.block.puzzle.games
com.unicostudio.braintestlegacy
com.halfbrick.fruitninjafree
com.halfbrick.boosterraiders
com.gafv.puzzle.game.classic.blockpuzzle.wood
com.mediocre.smashhit
com.halfbrick.jetpackjoyride
com.smilerlee.klondike
com.squareenix.relicrun
com.kiloo.subwaysurf
com.sybogames.subwaysurfers.match
com.outfit7.mytalkingtom2
com.match3blaster.DropStackBallFall
com.nekki.vector
com.outfit7.mytalkingangelafree
com.robtopx.geometryjumplite
com.gamma.checkers
com.unicostudio.braintest
com.firsttouchgames.dls7
com.imangi.templerun
com.vectorunit.red
Business
onlinejobs.opportunities.employment
com.evernote
com.pdf.reader.edit.pdf
cc.forestapp
com.mobisystems.office
com.indeed.android.jobsearch
com.qrscanner.readbarcode.qrreader.wifiqr.generator
arproductions.andrew.worklog
com.studzone.invoicegenerator
jobsearch.resumebuilder.findjobs.resumescan
com.weenysoft.word2pdf
org.kman.AquaMail
im.thebot.messenger
com.coinmarketcap.android
com.moneywink.emi
com.jojdevx.expense.tracker
com.indymobileapp.document.scanner
com.resume.builder.cv.maker.pdf
com.hnib.smslater
com.microsoft.office.outlook
com.signature.creator.stylish.name.maker.draw
com.colpit.diamondcoming.isavemoney
com.crm.leadmanager
com.documentscan.simplescan.scanpdf
com.svgapps.android.receiptmaker
net.smartlogic.indiagst
com.appmystique.businesscardmaker
alldocumentreader.office.viewer.filereader
com.catalinagroup.callrecorder
icv.resume.curriculumvitae
Dating
com.affinityapps.chispa
com.maybeyou
com.bluelionmobile.qeep.client.android
com.panda.likerro
com.mico
com.talknow.free.text.me.now.second.phone.number.burner.app
com.affinityapps.blk
com.jaumo.mature
com.dating.pheromance
enterprises.dating.boo
com.skout.android
com.onlyspark
com.chretiennekarima.dating
com.mobincube.usa_chat
com.hily.app
com.evermatch
com.videocalllive.piqo
com.cupidmedia.wrapper.afrointroductions
com.dating.lovector
com.jaumo
ru.fotostrana.sweetmeet
com.ftw_and_co.happn
ru.ok.android
app.blackgentry
com.myyearbook.m
com.chatever
com.cupidmedia.wrapper.bbwcupid
com.weez.datemechristian
com.pinkapp
com.affinityapps.twozerofour
com.ihappydate
net.lovoo.android
com.jaumo.prime
com.jaumo.casual
com.taggedapp
com.okcupid.okcupid
im.twogo.godroid
com.badoo.mobile
com.waplog.social
com.zoosk.zoosk
com.pof.android
com.tinder
app.bumpy.android
Music_and_Audio
music.disc.dj.mixer.music.mixer
com.musicplayer.mp3playerfree.audioplayerapp
com.musicdownloader.mp3downloadergo.descargar
com.search.music.mp3.musicplayer
com.tianxingjian.supersound
com.musicplayer.player.mp3player.white
com.offshore.picasso
audiocutter.videocutter.audiovideocutter
com.podbean.app.podcast
com.spotify.music
com.simp1emusic.free.music
sound.effect.equalizer.musicplayer
com.hungama.myplay.activity
free.mediaplayer.mp3.audio.music
musicplayer.playmusic.audioplayer
com.liveradio.fmradio.radiotuner.radiostation.amradio
com.Project100Pi.themusicplayer
com.mp3player.musicplayer.musicapps.music
com.sec.android.app.music
media.player.video.musicplayer
com.genius.android
com.music.ops.retroappdownload2
media.audioplayer.musicplayer
com.free.music.downloader.erersd
com.easybrain.make.music
com.bandlab.bandlab
audio.sound.effect.bass.virtrualizer.equalizer
com.podcast.podcasts
com.simplemobiletools.musicplayer
com.audiomack
musicplayer.musicapps.music.mp3player
LIfestyle
mydiary.journal.diary.diarywithlock.diaryjournal.secretdiary
com.bluesignum.bluediary
com.hrd.motivation
com.ibooktok.novel
com.adpog.diary
com.astrosouls
io.cordova.astromatrix
net.daylio
amazing.facts.trivia.psychology.knowledge.interesting.amazingfacts.animal.human.kids.fun.science.ultimate.philosophy
com.pinterest
com.ascent.affirmations.myaffirmations
genesis.nebula
com.ivuu
com.horoscope.dailyhoroscope.zodiac
horoscope.tarot.zodiac
en.un7qi3.forceteller
com.SunsideGames.TheBigGameOfPatterns
enliven.motivational.quotes
com.daiymannaword.flashapp
com.behefun.homemhmg
com.happyverse.diarywithlock
com.happify.happifyinc
com.krikasoft.motivationalquotes
habittracker.todolist.tickit.daily.planner
com.daily.journal.diary.lock.mood.tracker.free
studio.love.sweet.lessons.in.life.quotes
com.sensustech.smarttvcast
dailyhoroscope.horoscope.zodiac
com.mirofox.numerologija
com.fortune.astroguru
Productivity
monitor.kmv.multinotes
com.evernote
com.superbyte.studybunny
com.shikudo.focus.google
cc.forestapp
com.notetaker.quicknotes.note
com.simplemobiletools.calendar
com.ztnstudio.notepad
flashcards.words.words
com.digibites.calendar
com.appgenix.bizcal
com.levor.liferpgtasks
journal.notes.planner.starnest
io.instaforex.ff
com.flashkeyboard.leds
apps.r.calculator
com.lucky.notewidget
easynotes.notes.notepad.notebook.privatenotes.note
tidynotes.notepad.notes.notebook.note.checklist.todolist
com.komorebi.SimpleCalendar
com.pabrikaplikasi.tradingjournalmoneymanagement
net.fast_notepad_notes_app.fastnotepad
habittracker.todolist.tickit.daily.planner
com.jgc.pomodoro.focus.sessiontimer
ru.alexandermalikov.protectednotes
com.apptualizame.agendapersonalgratis
aanibrothers.smart.calender
com.calenderlatest.yami
org.whiteglow.keepmynotes
todolist.scheduleplanner.dailyplanner.todo.reminders
com.simplerion.springpink
com.simplerion.doiap
notes.notepad.checklist.calendar.todolist.notebook
Art_and_Design
com.hubx.imagination
com.medibang.android.paint.tablet
com.ichime.photo.editor.collage.maker
com.artgenerator.texttoimage.aiart.outpaiting
com.hangoverstudios.faceswap.ai.art.avatar.generator
com.vyroai.aiart
com.mindsync.aiphoto.aiart.photoeditor
com.jdpapps.textt1
com.moiseum.dailyart2
photo.editor.photoeditor.filtersforpictures
photo.beauty.sticker.ar.camera
com.artech.logomakerfreepro
com.bytestorm.artflow
com.vadeapps.frasesparastatus.criadorfrasesdemaloka
com.cerdillac.phototool
bueno.android.paint.my
com.cam001.selfie
com.artname.fontshadow.namemaker.font.nameart.textart.artmaker.wallpaper
com.vblast.flipaclip
com.color.by.number.paint.ly.pixel.art
splendid.postermaker.designer
com.imaginstudio.imagetools.pixellab
com.wavy.photoeditor.aiart.artgenerator
gallery.photo.vault.photogallery.album
fusion.developers.shirtdesign
in.loop.hdmakeover
jp.ne.ibis.ibispaintx.app
com.invitation.maker.birthday.card
com.SimplyEntertaining.fontrush
com.pixlr.express
Entertainment
com.star.mobile.video
com.github.igorkhlebunov.downloader.ifunny
com.novagecko.memedroid
video.downloader.roposodownloader
com.tvguidemobile
com.google.android.apps.youtube.music
com.takatak.videodownlaod
com.plexapp.android
com.justplay.app
com.zombodroid.MemeGenerator
tv.pluto.android
com.mediaradiance.shotshort
com.storymatrix.drama
com.spotify.music
com.eterno.shortvideos
com.graymatrix.did
com.vizio.vue.launcher
com.diginerds.radiohotstar
com.imdb.mobile
com.zyhwplatform.shortplay
tv.fubo.mobile
com.tubitv
com.vidio.android
com.freeshort.drama.reel
com.amazon.avod.thirdpartyclient
shortn.video
com.soundcloud.android
com.Beauchamp.Messenger.external
com.changdu.mobovideo
com.viki.android
com.netshort.abroad
com.google.android.apps.youtube.kids
live.shorttv.apps
com.media.zatashima.studio
com.snackvideodownloader.videodownloaderforsnackvideo
com.ressoapp.offline.musics
com.jio.myjio
bookofjokes.app
com.roku.remote
com.minireels.shortdrama
com.play.lucky.real.earn.money.free.fun.games.play.reward.income
com.cbs.app
tv.twitch.android.app
com.newleaf.app.android.victor
com.google.android.youtube
com.gargan.abismo
com.crunchyroll.crunchyroid
com.newreading.goodreels
com.avcrbt.funimate
beauty.hd.camera
com.standysoftware.colorstyle
com.styleseat.promobile
photo.beauty.sticker.ar.camera
com.sephora
com.scentbird
com.mobile.bizo.inpainting.clothes
com.ulta
com.arcsoft.perfect365
com.ipsy.mobile.production
com.tattoomaker.tattoodesign.drawing.photo
hairstyle.colorChanger.haircut_salon
com.lajeuneandassociatesllc.barberchopdev
com.studio360apps.mirror
beauty.skin.care.app
com.sec.android.mimage.photoretouching
com.sallybeauty.shop
com.artname.fontshadow.namemaker.font.nameart.textart.artmaker.wallpaper
com.nabilsoft.daily_hairstyles_for_girls
cover.maker.filter.selfie
cam.sweet.selfie.effect.camera
photo.cam.filter.beauty.effect
net.booksy.business
com.dressy.closet.android
com.follow.ElfCosmetics
net.booksy.customer
body.shape.beauty
com.android.dreams.phototable
com.rstream.haircare
com.fresha.Fresha
com.shanga.walli
launcher.d3d.droid13.launcher
com.bigwinepot.nwdn.international
com.color.launcher
com.newlook.launcher
launcher.d3d.effect.launcher
animals.wall7Fon
com.launcher.smart.cool.black.theme
launcher.pie.launcher
com.launcher.smart.threed.icon.theme
com.touchtype.swiftkey
com.gau.go.launcherex.s
com.flashkeyboard.leds
com.phonecall.callscreen.colorphone
com.appsfactory.realmewallpapers
ocean.wall7Fon
com.transsion.XOSLauncher
com.pixelkraft.edgelightcolors
com.launcher.smart.glow.butterfly.theme
com.mi.launcher.cool
com.thmobile.transparentwallpaper
launcher.d3d.launcher
com.blackwallshd.blackwallpapers
com.hd.cool.wallpapers
com.camera.x
com.launcher.smart.android.beta
net.zedge.android
com.actionlauncher.playstore
com.launcher.smart.android
net.xblacky.animexwallpaper
thxdroid.androidapp.translatepro
cn.danatech.xingseus
io.appp.sounds.grasshopper
com.appsci.tenwords
com.languagedrops.drops.international
com.kids.preschool.learning.games
air.nn.mobile.app.main
com.PYOPYO.StarTracker
hacking.learnhacking.learn.hack.ethicalhacking.programming.coding.hackerx.cybersecurity
homework.helper
com.english.spelling.correction.wordpronunciation
com.busuu.android.enc
com.breboucas.japonesparaviajar
com.languagelearning.tutor.speakfluently
com.holy.bible.study
com.hellotalk
com.memrise.android.memrisecompanion
com.myplantin.app
com.bonbongame.learn.colors.and.shapes.kids.games
com.sinyee.babybus.taxi
com.sololearn
games.bini.fun.color.girls.coloring.dolls
com.findplant.plantidentification
com.quizlet.quizletandroid
com.duolingo
com.deepstash
com.brainbow.peak.app
com.testgames.psyhologytests
com.dmvwrittentest.android
plant.identification.flower.tree.leaf.identifier.identify.cat.dog.breed.nature
com.codecerebrum.py_trivia
com.cyberdavinci.gptkeyboard
co.brainly
com.codeway.brainapp
com.agandeev.mathgames.free
com.bagatrix.mathway.android
thanhhang.qrcode.scanner
com.whitesof.periodictable
com.alison.mobile.flutter
word.riddles.guess.brain.test.tricky.puzzle.quiz.game.free
woofz.dog.training.app
com.GamesForKids.Mathgames.MultiplicationTables
com.astralerstudio.mydmv.android
com.getmimo
org.vinakids.ABC123
com.freeit.java
com.solvely.photo.math.solver.calculator.ai
com.t11.skyviewfree
Travel_and_local
com.shivmedia20.travelassistant
bls.filesmanager.easy
com.southwestairlines.mobile
com.transsion.filemanagerx
com.digitalchemy.currencyconverter
com.bus.busseatbooking
com.makemytrip
com.whereismytraingadi.trainstatus.livetrainlocation
com.confirmtkt.lite
com.kayak.android
com.amadeus.cmt.client.android
com.cf.flightsearch
com.xe.currency
com.app.abhibus
com.flightaware.android.liveFlightTracker
com.flightradar24free
com.wego.android
com.tranzmate
com.rayo.savecurrentlocation
com.justdial.search
ru.yandex.yandexnavi
com.indkorliwayaa.arindkrawau
com.metrocket.iexitapp
com.utrack.nationalexpress
com.roadtrippers
com.lufthansa.android.lufthansa
com.travelassistant.tripplanner.app
net.skyscanner.android.main
com.google.android.apps.mapslite
com.expedia.bookings
live.weather.vitality.local.channel.forecast
com.jpltech.hurricanetracker
com.jrustonapps.myearthquakealerts
com.handmark.expressweather
com.weather.Weather
com.wunderground.android.weather
com.roomthermometer.interior
com.timely.forecastradar.weather
com.weather.forecast.rain.snow
com.kellytechnology.NOAA_Now
life.channel.accurate.local.weather.forecast
com.apalon.weatherradar.free
com.weather.nold.forecast
com.accurate.weather.forecast.live
weather.forecast.rain.radar
com.localweather.radar.climate
com.accuweather.android
com.wftab.weather.forecast
com.anapaapps.android.windcompass
aplicacion.tiempo
com.apalon.weatherlive.free
com.pelmorex.WeatherEyeAndroid
com.jrustonapps.myhurricanetracker
com.probadosoft.moonphasecalendar
com.aviatorassistant.weather
com.neave.zoomearth
com.nautide.app
com.weather.free.forecast.dailyweather
live.weather.vitality.studio.forecast.widget
net.downsouthcustoms.trackit
Video_Players_and_Editors
video.player.videoplayer
maxplayer.mediaplayer.videoplayer
com.video_converter.video_compressor
com.xvideostudio.videoeditor
com.videoplayer.savevideo.hd
vidma.video.editor.videomaker
com.nexstreaming.app.kinemasterfree
glitchvideoeditor.videoeffects.glitchvideoeffect
mp3videoconverter.videotomp3.videotomp3converter
media.player.hd.video.player
com.mxtech.videoplayer.ad
com.tohsoft.music.mp3.mp3player
videoeditor.videomaker.videoeditorforyoutube
com.tas.video.player.full.hd
com.alightcreative.motion
com.quvideo.xiaoying
uplayer.video.player
com.splice.video.editor
com.ryzenrise.vlogstar
media.audioplayer.musicplayer
video.player.audio.player.music
com.cyberlink.powerdirector.DRA140225_01
com.camerasideas.instashot
com.playit.videoplayer
com.rocks.music.videoplayer
media.video.music.musicplayer
com.kmplayer
com.video.glitcheffect
com.camerasideas.trimmer
rocks.video.videoplayer
com.progdigy.cdisplay.free
apps.android.books.comicx.comicbooks
com.lezhin.comics
com.tapastic
com.oriental.android.flyinglines
mobi.mangatoon.novel.portuguese
com.nhn.android.webtoon
com.naver.linewebtoon
com.csmart.cartooncomic.stripmaker
com.webcomics.manga
com.mangainc.app
com.radio.pocketfm
com.us.president.security.car.game
com.kodansha.kmanga
com.wb.goog.injustice.brawler2017
com.inkr.comics
com.toomics.global.google
ru.androidtools.comic_book_magazine_reader_cbr_cbz
com.qubitart.mangaguys
com.qidian.Int.reader
com.comikey.banagher
com.lalatoon.android
com.contentsfirst.tappytoon
com.comikin.reader10
com.pratilipi.comics
jp.co.shueisha.mangaplus
com.viewer.comicscreen
com.studiotrelle.mangacomic
com.crunchyroll.crunchyroid
com.avatarmaker.cartoonmaker
beauty.hd.camera
video.reface.app
com.lightx
photo.editor.photoeditor.filtersforpictures
online.passportphoto.visa.id.app
com.bigwinepot.nwdn.international
com.cardinalblue.piccollage.google
photocreation.camera.blurcamera
editingapp.pictureeditor.photoeditor
photo.filter.selfie.beauty.camera
com.arcsoft.perfect365
vsin.t16_funny_photo
com.intermedia.hd.camera.professional
photo.editor.photoeditor.photoeditorpro
com.camera.mix.camera
com.sec.android.mimage.photoretouching
com.magicv.airbrush
photo.gallery.photoeditor.photo.album
com.cyberlink.youperfect
gallery.hidepictures.photovault.lockgallery
photo.cam.filter.beauty.effect
com.accordion.prettyo
com.lightricks.facetune.free
photo.manager.private.photogallery
com.magic.retouch
net.sourceforge.opencamera
com.camerasideas.instashot
gallery.photo.vault.photogallery.album
com.gallery.easy.photo.editor.album.lyrical.video.status.maker
hd.camera
com.lensesdev.manual.camera.professional
com.footej.camera2
com.picsart.studio
House_and_Home
com.osfunapps.remoteforsamsung
com.trulia.android.rentals
com.toolslab.spycameradetector
com.boost.samsung.remote
ai.interior.design.home.renovation.app
com.kapron.ap.hotspot
co.vulcanlabs.samsungremote
com.houzz.app
tech.simha.androidtvremote
com.kraftwerk9.remotie
com.toolslab.remotesamsungtv
com.dontforgetthespoon.dont_forget_the_spoon
com.crowdstar.covetHome
com.remoteTechs.samsungremote
com.myplantin.app
com.housedesing.homeplanner.floorplan
com.kitchensketches
hueledlight.remotecontrol.smartapp
com.bonc.paintmyroom
au.com.realestate.app
com.colorsnap
com.looploop.tody
com.manqala.estatemanager
cam.camy
com.planner5d.planner5d
com.smart.remotehue.light.controller
com.pas.webcam
cz.master.lois
controller.light.philipshue.remote
com.smartwidgetlabs.philipshue
com.blodhgard.easybudget
net.yecode.cash_app
com.benoitletondor.easybudgetapp
com.hiatus.android
com.grppl.android.shell.CMBlloydsTSB73
com.realbyteapps.moneymanagerfree
com.tribab.tricount.android
network.xyo.coin
com.yahoo.mobile.client.android.finance
com.monefy.app.lite
in.sweatco.app
com.iproyal.android
com.freeman.moneymanager
com.xe.currency
crypto.bitcoin.ethereum.litecoin.cloud.mining.eth.btc.ltc.hash.pool.cloud_mining
com.jaydip.nfcreader
ru.innim.my_finance
com.expensetracker.myfewcents
com.marketwatch
com.cardsapp.android
com.kpmoney.android
com.kiqqi.laai
incomeexpense.incomeexpense
com.icready.app.databanky
com.uvnv.mintsim
com.smartswitch.phoneclone.datatransfer.fileshare.sendanywhereapp
com.bloomberg.android.plus
com.integer.cse
com.expensemanager
"""

def search_logs(file_paths, search_terms):
    """
    Searches the provided list of log file paths for the search terms.
    Returns a set of unique matches found.
    """
    matches_found = set()

    print(f"Scanning {len(file_paths)} log file(s) for {len(search_terms)} directory names...")

    for log_path in file_paths:
        try:
            # Open with utf-8, ignore errors to handle potential binary garbage in logs
            with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                
                for term in search_terms:
                    # Check if the directory name exists in the file content
                    if term in content:
                        matches_found.add(term)
                        
        except Exception as e:
            print(f"Could not read file {log_path}: {e}")

    return matches_found

def main():
    # Configuration
    logs_dir = "logcat_logs"

    print("--- Starting Analysis ---")
    print(f"Log Directory:    {os.path.abspath(logs_dir)}")
    
    # 1. Process the Raw List
    # We split by newlines, strip whitespace, and ignore empty lines.
    # We also filter for items containing '.' to avoid searching for category headers like "Shopping"
    target_names = [line.strip() for line in TARGET_LIST_RAW.splitlines() if line.strip() and '.' in line]
    
    if not target_names:
        print("No valid package names found in the target list. Exiting.")
        return

    print(f"Loaded {len(target_names)} specific packages to search for (e.g., '{target_names[0]}').")

    # 2. Select Log File
    if not os.path.exists(logs_dir):
        print(f"Error: The directory '{logs_dir}' does not exist.")
        return

    try:
        all_files = [f for f in os.listdir(logs_dir) 
                     if os.path.isfile(os.path.join(logs_dir, f)) and f.lower().endswith('.log')]
    except Exception as e:
        print(f"Error reading log directory: {e}")
        return

    if not all_files:
        print(f"No .log files found in '{logs_dir}'.")
        return

    print("\nAvailable Log Files:")
    for i, f in enumerate(all_files):
        print(f"{i + 1}. {f}")

    try:
        choice_idx = int(input("\nEnter the number of the log file to analyze: ")) - 1
        
        if 0 <= choice_idx < len(all_files):
            selected_file = all_files[choice_idx]
            files_to_search = [os.path.join(logs_dir, selected_file)]
            
            # 3. Search Logs
            unique_matches = search_logs(files_to_search, target_names)

            # 4. Output Results
            print("\n--- Search Results ---")
            if unique_matches:
                print(f"Found {len(unique_matches)} unique matches in '{selected_file}':")
                for match in sorted(unique_matches):
                    print(f"MATCH: {match}")
            else:
                print(f"No matches found in '{selected_file}'.")
        else:
            print("Invalid selection number.")

    except ValueError:
        print("Invalid input. Please enter a number.")

if __name__ == "__main__":
    main()
